{% set version = "2017.2.0" %}

package:
  name: libadjoint
  version: {{ version }}

source:
  url: https://bitbucket.org/dolfin-adjoint/libadjoint/downloads/libadjoint-{{ version }}.tar.gz
  sha256: 01f49c13f07a1ae3f2f28c2a8890b41ac53ab4bdc31073fab9cece85e25f794d

build:
  number: 1013
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make   # [unix]
  host:
    - python
    - mpich
    - petsc
    - slepc
  run:
    - python
    - mpich
    - petsc
    - slepc
    - six
    - numpy

test:
  imports:
    - libadjoint

about:
  home: http://www.dolfin-adjoint.org/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: 'library for the high-level algorithmic differentiation of scientific models'

  description: |
    libadjoint is a library for the high-level algorithmic differentiation of
    scientific models. It's mainly used by dolfin-adjoint.
  doc_url: http://www.dolfin-adjoint.org/en/latest/documentation/index.html
  dev_url: https://bitbucket.org/dolfin-adjoint/libadjoint

extra:
  recipe-maintainers:
    - johannesring
    - funsim
    - minrk
