{% set version = "2017.2.0" %}
{% set sha256 = "01f49c13f07a1ae3f2f28c2a8890b41ac53ab4bdc31073fab9cece85e25f794d" %}

{% set petsc_version = '3.8.*' %}
{% set slepc_version = '3.8.*' %}

package:
  name: libadjoint
  version: {{ version }}

source:
  fn: libadjoint-{{ version }}.tar.gz
  url: https://bitbucket.org/dolfin-adjoint/libadjoint/downloads/libadjoint-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - cmake
    - toolchain
    - mpich
    - petsc {{ petsc_version }}
    - slepc {{ slepc_version }}
  run:
    - python
    - mpich
    - petsc {{ petsc_version }}
    - slepc {{ slepc_version }}
    - six
    - numpy

test:
  imports:
    - libadjoint

about:
  home: http://www.dolfin-adjoint.org/
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'library for the high-level algorithmic differentiation of scientific models'

  description: |
    libadjoint is a library for the high-level algorithmic differentiation of
    scientific models. It's mainly used by dolfin-adjoint.
  doc_url: http://www.dolfin-adjoint.org/en/latest/documentation/index.html
  dev_url: https://bitbucket.org/dolfin-adjoint/libadjoint

extra:
  recipe-maintainers:
    - johannesring
    - funsim
