travis:
  secure:
    BINSTAR_TOKEN: fI5aUXQtfE0Dgnuxh/F1AyqcQ75GoeN39shJKUCTyFj61/tbroOC1EpwEGDlerSSGNJUcptOywNHPSaWRPTFO0KJwi9bjo75osLXxD4cQn9EA/sazLC9C1aC7FnWWb6M8nRYCjBKwKPXS+kUmI8kPEp5SCihay/XHnM6p/hkVfAo1fNI3h97Db55fFVDzRBklq65IWfPD1sjermdKVOU183CLrVanKzewlpgX4oKkaQNchvcvo6OoDEh0eFlgZO3K+q/6q4iDe9hgaDWjMrruj6n9Vo8lwX8Gj84n9ETlSSWNe+Ov4C4eayVx9aUjJuXhI5JfpACEcFbVOGkIQ/QCf7wtJut9ZJxpU4hSnBOqudiyAzhCNaNU91BBxF/7nMgxiEp2YK3ClHCY1Vfms5gHOfsSrIAwfTAGvYkxSKg2tg4mwtF5KQCB/SRAFeHHzKyjS7YfEIwXNSliPa0Qxs6lqJHHbYTZVNdoTGqN+EmchTR5sL8ITZHAsDubp0ho1TztQtJcV/RJbzPQ0nsEiPjz8lIXh5DouLMyBCmK6HhBVrU0zCa9dwb9khi0GQpuT7HO0SyiO4lcVvBgqLs9Ny3rY9LkKfVzKyF4Vr4CpEXB+DKZ6UmAICoTG4vwEKLbRR+nhQRD22vU2nd5OrYia52iK1d2m01gGWV2ZzmQqs+ePY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
